### ISSUE TITLE
Dispatch a event on copy?

### ISSUE THREAD

**Issue by johnhult** [Jarvis1010/react-copy-code#1]
Hi! This works like a charm. Was only wondering if it would be possible to add an event when copying. Would like to add a notification when code is copied.

**Comment by Jarvis1010** [comment]
This is a great idea!  Should definitely look into doing that

**Comment by Jarvis1010** [comment]
you can now pass a function to an `onCopy` prop on the CodeBlock component and it will run that function when the copy is clicked
